GET http://localhost:3000/auth

### Login admin 
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "username":"henasdak",
    "email":"deez@gmail.com",
    "password":"henk123"
}

