GET http://localhost:3000/auth

### Register user 
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "username":"henasdak",
    "email":"deez@gmail.com",
    "password":"henk123321"
}

### login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"deez@gmail.com",
    "password":"henk123321"

}

### admin user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"admin"
}




