GET http://localhost:3000

### login as standard user
POST http://localhost:3000/auth
Content-Type: application/json
Accept: application/json

{
  "username":"henk",
  "email":"henk@gmail.com",
  "password":"henk123"
}
> {%
client.global.set("token", response.body.token);

client.test("Request executed succesfully", function(){
    client.assert(response.status === 200, "Response status is not 200, "  + response.status)
});

client.test("Check body" , function(){
    client.assert(response.body.token, "There is no JSON token")
});

client.test("Response content-type is json" , function(){
    const type = response.contentType.mimeType;
    client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'" )
})
%}

### set global user token
 GET http://localhost:3000/resource/{{token}}
 Content-Type: application/json
 Authorization: bearer {{token}}

> {%
 client.test("Request executed succesfully", function(){
    client.assert(response.status === 200, "Response status is not 200, "  + response.status)
});
 %}