GET http://localhost:3000/user
Content-Type: application/json
Accept: application/json

### login
POST http://localhost:3000/auth

Content-Type: application/json

{
"username":"henk",
"email":"henk@gmail.com",
"password":"henk123"
}