### User adds auction (user not admin)
POST http://localhost:3000/register/
Content-Type: application/json
Accept: application/json

{
  "username":"descarts",
  "email":"utrecht@gmail.com",
  "password": "draw"
}

> {%
 client.test("Request executed succesfully", function(){
    client.assert(response.status === 200, "Response status is not 200, "  + response.status)
});
 client.test("Check body" , function(){
    client.assert(response.body.user, "There is no items")
});
 %}

### Username not specified
POST http://localhost:3000/register/
Content-Type: application/json
Accept: application/json

{
  "email":"utreceht@gmail.com",
  "password": "draw"
}

> {%
 client.test("Request executed succesfully", function(){
    client.assert(response.status === 404, "Response status is not 200, "  + response.status)
});
 client.test("Check body" , function(){
    client.assert(response.body.error, "There is no items")
});
 %}


### info already exist
POST http://localhost:3000/register/
Content-Type: application/json
Accept: application/json

{
  "username":"descarts",
  "email":"henk3@gmail.com",
  "password": "draw"
}

> {%
 client.test("Request executed succesfully", function(){
    client.assert(response.status === 200, "Response status is not 200, "  + response.status)
});
 client.test("Check body" , function(){
    client.assert(response.body.user, "There is no items")
});
 %}